<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/main.css">
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <h2>User registration</h2>
            <hr>
            <div class="form-horizontal">
                <div class="form-group">
                    <input type="hidden" id="user_id" disabled><br>
                    <label class="control-label col-sm-4" for="first_name">First Name:</label>
                    <div class="col-sm-8">
                        <input type="text" id="first_name" /><br>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-4" for="last_name">Last Name:</label>
                    <div class="col-sm-8">
                        <input type="text" id="last_name" /><br>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-4" for="address">Address:</label>
                    <div class="col-sm-8">
                        <input type="text" id="address" /><br>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button class="btn btn-default" onclick="save()">Save</button>
                    </div>
                </div>
            </div>
            <hr>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Address</th>
                    </tr>
                </thead>
                <tbody id="usersList">
                    <tr>
                        <td></td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</body>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>
<script src="static/js/main.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</html>